import { mkdirSync, readFileSync, realpathSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { pathToFileURL } from "node:url";

export function extractExportedFunctions(headerText) {
  const names = new Set();
  const parts = headerText.split("LEPT_DLL extern");
  for (let i = 1; i < parts.length; i++) {
    const decl = parts[i].split(";")[0];
    const fnPtr = /\(\s*\*\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(/.exec(decl);
    if (fnPtr && !decl.slice(0, fnPtr.index).includes("(")) continue;
    const plain = /\b([A-Za-z_][A-Za-z0-9_]*)\s*\(/.exec(decl);
    if (plain) names.add("_" + plain[1]);
  }
  return [...names].sort();
}

/**
 * Loose d.ts for the raw layer (design §6): name-level symbol presence with
 * a single loose signature per symbol. Arity is deliberately NOT encoded —
 * the curated signature source is the emit-tsd WasmModule interface in
 * dist/full-abi/leptonica.d.ts; this file answers "which symbols exist",
 * not "what are their exact types".
 */
export function renderLooseDts(names) {
  const lines = [
    "// Generated by gen-exports.mjs — loose raw-layer d.ts (design §6).",
    "// Consumer-facing type of the leptonica-wasm/full-abi/leptonica.mjs",
    "// subpath export. Every symbol carries one loose signature; the precise",
    "// C signature lives in allheaders.h, and the emit-tsd WasmModule",
    "// interface carries exact arity.",
    "",
    "export interface RawSymbols {",
  ];
  for (const name of names) {
    lines.push(`  readonly ${name}: (...args: number[]) => number | void;`);
  }
  lines.push(
    "}",
    "",
    "/** Emscripten module-arg subset loadRaw relies on. */",
    "export interface EmscriptenModuleArg {",
    "  wasmBinary?: ArrayBuffer | Uint8Array;",
    "  instantiateWasm?(",
    "    imports: WebAssembly.Imports,",
    "    receiveInstance: (instance: WebAssembly.Instance) => void,",
    "  ): unknown;",
    "  [key: string]: unknown;",
    "}",
    "",
    "/** The Emscripten factory; the returned module satisfies RawSymbols. */",
    "declare const factory: (moduleArg?: EmscriptenModuleArg) => Promise<RawSymbols & Record<string, unknown>>;",
    "",
    "export default factory;",
    "",
  );
  return lines.join("\n");
}

function usage() {
  console.error("usage: node gen-exports.mjs <header.h> [--out <file>] [--dts-out <file>]");
}

const isMain = (() => {
  try {
    return import.meta.url === pathToFileURL(realpathSync(process.argv[1])).href;
  } catch {
    return false;
  }
})();

if (isMain) {
  const args = process.argv.slice(2);
  let outPath = null;
  let dtsOutPath = null;
  const positional = [];
  for (let i = 0; i < args.length; i++) {
    if (args[i] === "--out") {
      outPath = args[i + 1] ?? null;
      if (outPath === null) {
        usage();
        process.exit(2);
      }
      i++;
    } else if (args[i] === "--dts-out") {
      dtsOutPath = args[i + 1] ?? null;
      if (dtsOutPath === null) {
        usage();
        process.exit(2);
      }
      i++;
    } else if (args[i].startsWith("--")) {
      usage();
      process.exit(2);
    } else {
      positional.push(args[i]);
    }
  }
  if (positional.length !== 1 || !positional[0].endsWith(".h")) {
    usage();
    process.exit(2);
  }
  const names = extractExportedFunctions(readFileSync(positional[0], "utf8"));
  const payload = JSON.stringify(names) + "\n";
  if (outPath) {
    mkdirSync(dirname(resolve(outPath)), { recursive: true });
    writeFileSync(outPath, payload);
    console.error(`wrote ${names.length} exported functions to ${outPath}`);
  } else {
    process.stdout.write(payload);
  }
  if (dtsOutPath) {
    mkdirSync(dirname(resolve(dtsOutPath)), { recursive: true });
    writeFileSync(dtsOutPath, renderLooseDts(names));
    console.error(`wrote loose d.ts (${names.length} symbols) to ${dtsOutPath}`);
  }
}
